### ISSUE TITLE
[Error] Unexpected argument --gas-price found (TestNet)

### ISSUE THREAD

**Issue by saitgulmez** [make-software/how-to-casperlabs#107]
Hi,
This is about node installation in the TestNet. Following command in the installation guide does not work properly.

```
sudo -u casper casper-client put-deploy \
    --chain-name "$CHAIN_NAME" \
    --node-address "http://127.0.0.1:7777/" \
    --secret-key "/etc/casper/validator_keys/secret_key.pem" \
    --session-path "$HOME/casper-node/target/wasm32-unknown-unknown/release/add_bid.wasm" \
    --payment-amount 7500000000 \
    --gas-price=1 \
    --session-arg=public_key:"public_key='$PUBLIC_KEY_HEX'" \
    --session-arg=amount:"u512='900000000000'" \
    --session-arg=delegation_rate:"u8='1'"
```

**What can be done to solve this problem?**
    If --gas-price argument is omitted from the above script, it will work without any error.

From the [documentation](https://docs.casper.network/operators/becoming-a-validator/bonding/)  **--payment-amount** is 2500000000 but  it is assigned to 7500000000 in the testnet documentation.  By the way, this does not cause any problem.

![Binding_Node_To_The_Network](https://github.com/make-software/how-to-casperlabs/assets/18303197/58fe1b26-ac7b-4d8e-b733-70412e321d21)

**Comment by mrkara** [comment]
@saitgulmez Thank a lot for the detailed issue report! :)

A pull request to fix this issue is now in review.
