### ISSUE TITLE
Add "git" + "software-properties-common" to the installation how-tos

### ISSUE THREAD

**Issue by GuybrushX** [make-software/how-to-casperlabs#52]
On a freshly installed system with Ubuntu via the Hetzner installimage tool the following two apt packages were missing:
git
software-properties-common (needed for apt-add-repository)

Please add them to the how-tos to be sure that the steps can be ran with all requirements installed.

**Comment by mrkara** [comment]
@GuybrushX Thanks a lot for the feedback! Should be fixed soon.
