### ISSUE TITLE
It seems like the first validator in the mainnet known_validators list is rejecting port 7777

### ISSUE THREAD

**Issue by davidtai** [make-software/how-to-casperlabs#72]
While setting up a new node, I ran this command:
`casper-client get-block --node-address http://$KNOWN_VALIDATOR_IP:7777 -b 20`

I get:
Failed to get RPC response: error sending request for url (http://139.162.132.144:7777/rpc): error trying to connect: tcp connect error: Connection refused (os error 111)

This is on ubuntu 20.04.  I had to manually set it to another validator in the list:
`KNOWN_VALIDATOR_IP=135.181.165.110`

Instructions should be modified to account for picking a validator with 7777 unblocked.

**Comment by ihor** [comment]
@mssteuer we discussed it with @mrkara some time ago and the solution is to hardcore the block hash. We are fetching the 20th block on the network and it's always the same.

**Comment by mrkara** [comment]
@ihor In fact, the looping idea seems like a better one after looking at the instructions. That part is shared among the Mainnet and the Testnet, and a loop will work always for both cases.
